### ISSUE TITLE
Landmarks and Checkpoint 

### ISSUE THREAD

**Issue by argha0x** [luca-morreale/neural_surface_maps#1]
We have the following lines in the **train_intersurface_map.py**
SURFACE_PATH_F  = '/SET/HERE/YOUR/PATH'
SURFACE_PATH_G  = '/SET/HERE/YOUR/PATH'
CHECKPOINT_PATH = '/SET/HERE/YOUR/PATH'
landmarks_g     = []
landmarks_f     = []

I have done Steps 1-4 for the source and the target mesh, thus I have two neural surface representation at
 _output/parametrization_[timestamp]/_ for the source map and  _output/parametrization_[timestamp]/_ for the target map.

Do I need to provide the path of the **pth** file inside _output/parametrization_[timestamp]/_ for SURFACE_PATH_G and SURFACE_PATH_F ?

What is CHECKPOINT_PATH and how can I get the landmarks for the two meshes?

What are the landmarks for Bimba to Beethoven example?

**Comment by luca-morreale** [comment]
Hello Argha,
thank you for the question.

Those variables are present in `show_intersurface_map.py` and not in `train_intersurface_map.py`. You can run `show_intersurface_map.py` **only after** you have trained a inter-surface map.

After you have an intersurface map, to visualize it you must set `SURFACE_PATH_F` and `SURFACE_PATH_G` to `.pth` files of the two surfaces (`overfit_[timestamp]`). 
`CHECKPOINT_PATH` instead is the path to the intersurface map you computed (`intersurface_[timestamp]`).

The landmarks are a list of vertex indices. In my experiments I selected 1 point on the nose and 1 point for each shoulder.
These should be the landmarks for beethoven: `22335, 4982, 11633` and these for bimba: `14505,  182, 12108`. Please double check.

Please, let me know if this solves your problem.
