### ISSUE TITLE
Errors in reproducing results correctly by training models

### ISSUE THREAD

**Issue by VolgZangeif** [luca-morreale/neural_surface_maps#2]
I tried running the code using the given checkpoints and was able to verify the results.
The meshes obtained with texture applied are as follows:

<img width="1187" alt="bimba_beethoven_pre_trained_models" src="https://user-images.githubusercontent.com/42914919/156042449-6ab54b8b-3991-496b-a23b-b15a6e6aa157.png">

But when I tried steps 2-5 on my own, I received some inconsistent results. The inter-surface maps were a bit off. I have attached screenshots with texture applied on them

![bimba_beethoven_trained_models](https://user-images.githubusercontent.com/42914919/155988864-ffa3ce7a-746f-4afc-8443-45fc5a698956.png)

As can be seen, the mapping on the nose and the shoulder is a bit off center. The same is true for the other shoulder. I have uploaded the intersurface maps obtained in the link [here](https://drive.google.com/drive/folders/17AdOUNBsGtprCs9UJfwnRzPbpPOuVfcL?usp=sharing)

This happened on multiple runs of the model and I am unable to figure out whether something is wrong with the way I am running the code or not.

The steps I followed to obtain the model were as follows:
1) Create output_sample.pth for bimba and beethoven models using the given parametrised mesh and their corresponding oversampled versions.
2) Train a surface map using given output_sample.pth files. The config files given to hydra were unchanged.
3) Create parameterisation map using the surface map of bimba and beethoven
4) Create intersurface map using the surface map of bimba and beethoven
5) Visualise the maps as meshes using show_surface_map, show_param_map, and show_intersurface_map.

**Comment by luca-morreale** [comment]
Hello,
the textures are clearly misaligned.
Did you set the landmarks for the two surfaces?
The configuration file has `landmarks_g` and `landmarks_f` to set. The default value is an empty list.
For example:
```
landmarks_f : [22335, 4982, 11633]
landmarks_g : [14505,  182, 12108]
```

I did forget to mention this in the README file, apologies.

**Comment by VolgZangeif** [comment]
I did use the landmarks as mentioned(it was also mentioned in [a comment to a previous issue](https://github.com/luca-morreale/neural_surface_maps/issues/1#issuecomment-953662677)).
Because of this, I was able to get correct texture mapping as shown in the first figure. But using the same landmarks for a model retrained on the same data, I got results as shown in the second figure.
